openapi: 3.0.0
info:
  title: audit_manager
  version: v1
  description: Log manager for the Utelly API platform
servers:
  - url: 'https://services.utelly.com/audit_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/audit_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/audit_manager/v1'
    description: dev
paths:
  /log:
    post:
      summary: Add a Log entry
      operationId: v1.log.post_log
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status_code:
                    type: integer
                  log:
                    $ref: ../models/Log.v1.yaml
                required:
                  - status_code
                  - log
              examples:
                '1':
                  value:
                    status_code: 200
                    log:
                      timestamp: 1583934547
                      user_id: 4ae0359e57bf4465b79d730d27f84426
                      system_name: user_manager
                      system_version: 2
                      code: pipeline_success
                      payload:
                        message: pipeline successfully created
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Log.v1.yaml
            examples:
              '1':
                value:
                  timestamp: 1583934547
                  user_id: 4ae0359e57bf4465b79d730d27f84426
                  system_name: user_manager
                  system_version: 2
                  code: pipeline_success
                  payload:
                    message: pipeline successfully created
      security:
        - Authorization: []
      description: Add a Log entry
      tags:
        - Audit Management
  /logs:
    post:
      summary: Batch add Log entries
      operationId: v1.logs.post_logs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  status_code:
                    type: number
                  logs:
                    type: array
                    items:
                      $ref: ../models/Log.v1.yaml
                required:
                  - status_code
                  - logs
              examples:
                '1':
                  value:
                    status_code: 200
                    logs:
                      - timestamp: 1583934547
                        user_id: 4ae0359e57bf4465b79d730d27f84426
                        system_name: user_manager
                        system_version: 2
                        code: pipeline_success
                        payload:
                          message: pipeline successfully created
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              uniqueItems: false
              items:
                $ref: ../models/Log.v1.yaml
            examples:
              '1':
                value:
                  - timestamp: 1583934547
                    user_id: 4ae0359e57bf4465b79d730d27f84426
                    system_name: user_manager
                    system_version: 2
                    code: pipeline_success
                    payload:
                      message: pipeline successfully created
        description: ''
      description: Batch add Log entries
      parameters: []
      tags:
        - Audit Management
    parameters: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      description: ''
      x-apikeyInfoFunc: security.check_token
