openapi: 3.0.0
info:
  title: broker_app
  version: v1
  description: "Use the url by clicking the Mock url CTA.\n\nexample for login users:\n\ncurl --request POST \\\n  --url https://stoplight.io/p/mocks/12076/66030/login \\\n  --header 'content-type: application/json' \\\n  --data '{\"email\":\"test@email.com\",\"password\":\"password\"}'\n"
servers:
  - url: 'https://services.utelly.com/broker_app/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/broker_app/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/broker_app/v1'
    description: dev
paths:
  /login:
    post:
      summary: User Login
      operationId: v1.user.login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  roles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Role'
                  refresh_token:
                    type: string
                required:
                  - id
                  - access_token
                  - roles
                  - refresh_token
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    access_token: 9b38b54dd74644db96e772d6076615da
                    refresh_token: f9a664c1ba3f4665aa902ded47edaca9
                    roles:
                      - perspective_id: 1
                        module_id: 1
                        environment_id: 1
                        permission: login_to_portal
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            examples:
              '1':
                value:
                  email: hello@utelly.com
                  password: 3@Ubc1iCYZUKGtAi
      tags:
        - User Management
  /refresh_jwt_token:
    post:
      summary: Refresh access_token
      operationId: v1.user.refresh_jwt_token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                required:
                  - access_token
              examples:
                '1':
                  value:
                    access_token: f9a664c1ba3f4665aa902ded47edaca9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
            examples:
              '1':
                value:
                  refresh_token: cc53ca4aaf294c489a29c1515cb1f1b3
      description: ''
    parameters: []
components:
  schemas:
    Role:
      title: Role
      type: object
      x-examples:
        '1':
          perspective_id: 1
          module_id: 1
          environment_id: 1
          permission: login_to_portal
      properties:
        environment_id:
          type: integer
        perspective_id:
          type: integer
        module_id:
          type: integer
        permission:
          type: string
      required:
        - environment_id
        - perspective_id
        - module_id
        - permission
  securitySchemes: {}
