openapi: 3.0.0
info:
  title: broker_app
  version: v1
  description: "Use the url by clicking the Mock url CTA.\n\nexample for login users:\n\ncurl --request POST \\\n  --url https://stoplight.io/p/mocks/12076/66030/login \\\n  --header 'content-type: application/json' \\\n  --data '{\"email\":\"test@email.com\",\"password\":\"password\"}'\n"
servers:
  - url: 'https://services.utelly.com/broker_app/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/broker_app/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/broker_app/v1'
    description: dev
paths:
  /login:
    post:
      summary: User Login
      operationId: v1.user.login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  roles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Role'
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    access_token: 9b38b54dd74644db96e772d6076615da
                    refresh_token: f9a664c1ba3f4665aa902ded47edaca9
                    roles:
                      - perspective_id: 1
                        module_id: 1
                        environment_id: 1
                        permission: login_to_portal
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            examples:
              '1':
                value:
                  email: hello@utelly.com
                  password: 3@Ubc1iCYZUKGtAi
      tags:
        - User Management
  /refresh_jwt_access_token:
    post:
      summary: Refresh JWT access_token
      operationId: v1.user.refresh_jwt_access_token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                required:
                  - access_token
              examples:
                '1':
                  value:
                    access_token: f9a664c1ba3f4665aa902ded47edaca9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
            examples:
              '1':
                value:
                  refresh_token: cc53ca4aaf294c489a29c1515cb1f1b3
      description: ''
      tags:
        - User Management
    parameters: []
  /register:
    post:
      summary: User Register
      operationId: v1.user.register
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                  roles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Role'
                required:
                  - id
                  - access_token
                  - refresh_token
                  - roles
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    access_token: 9b38b54dd74644db96e772d6076615da
                    refresh_token: f9a664c1ba3f4665aa902ded47edaca9
                    roles:
                      - perspective_id: 1
                        module_id: 1
                        environment_id: 1
                        permission: login_to_portal
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                registration_token:
                  type: string
                password:
                  type: string
                password_confirm:
                  type: string
              required:
                - first_name
                - last_name
                - email
                - registration_token
                - password
                - password_confirm
            examples:
              '1':
                value:
                  first_name: Keizer
                  last_name: Söze
                  email: keizer@email.com
                  registration_token: 55a68d8af89b4a29a453c9a21b37445f
                  password: password
                  password_confirm: password
  /forgot_password:
    post:
      summary: ''
      operationId: v1.user.forgot_password
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                destination_url_template:
                  type: string
              required:
                - email
                - destination_url_template
            examples:
              '1':
                value:
                  email: keiser@email.com
                  destination_url_template: 'https://mydomain.com/forgot_password_page?email={email}&token={token}'
      description: sends an email with a authentication token
  /forgot_password_confirm:
    post:
      summary: ''
      operationId: v1.user.forgot_password_confirm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                password:
                  type: string
                password_confirm:
                  type: string
              required:
                - email
                - token
            examples:
              '1':
                value:
                  email: keiser@email.com
                  token: 1e5b4fa91553455aa3e3e1b33928a6cd
                  password: password
                  password_config: password
      responses:
        '200':
          description: OK
components:
  schemas:
    Role:
      title: Role
      type: object
      x-examples:
        '1':
          perspective_id: 1
          module_id: 1
          environment_id: 1
          permission: login_to_portal
      properties:
        environment_id:
          type: integer
        perspective_id:
          type: integer
        module_id:
          type: integer
        permission:
          type: string
      required:
        - environment_id
        - perspective_id
        - module_id
        - permission
  securitySchemes: {}
