openapi: 3.0.0
info:
  title: broker_app
  version: v1
servers:
  - url: 'https://services.utelly.com/broker_app/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/broker_app/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/broker_app/v1'
    description: dev
paths:
  /login:
    post:
      summary: User Login
      operationId: v1.user.login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  authentication_token:
                    type: string
                  roles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Role'
                required:
                  - id
                  - authentication_token
                  - roles
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    authentication_token: 9b38b54dd74644db96e772d6076615da
                    roles:
                      - perspective_id: 1
                        module_id: 1
                        environment_id: 1
                        permission: login_to_portal
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            examples:
              '1':
                value:
                  email: hello@utelly.com
                  password: 3@Ubc1iCYZUKGtAi
      tags:
        - User Management
  /register:
    post:
      summary: User Register
      operationId: v1.user.register
      responses:
        '200':
          description: OK
      tags:
        - User Management
components:
  schemas:
    Role:
      title: Role
      type: object
      x-examples:
        '1':
          perspective_id: 1
          module_id: 1
          environment_id: 1
          permission: login_to_portal
      properties:
        environment_id:
          type: integer
        perspective_id:
          type: integer
        module_id:
          type: integer
        permission:
          type: string
      required:
        - environment_id
        - perspective_id
        - module_id
        - permission
