openapi: 3.0.0
info:
  title: configuration_manager
  version: v1
servers:
  - url: 'https://services.utelly.com/configuration_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/configuration_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/configuration_manager/v1'
    description: dev
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: query
paths:
  '/environment/{environment_id}/view/{view_id}':
    parameters:
      - schema:
          type: string
        name: environment_id
        in: path
        required: true
      - schema:
          type: string
        name: view_id
        in: path
        required: true
    get:
      summary: Get configurations
      tags: []
      operationId: v1.configs.get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Configuration.v1.yaml
      security:
        - Authorization: []
      description: ''
