components:
  schemas: {}
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: security.check_token
info:
  title: configuration_manager
  version: v1
openapi: 3.0.0
paths:
  /environment/{environment_id}/view/{view_id}:
    get:
      description: ''
      operationId: v1.configs.get
      responses:
        '200':
          content:
            application/json:
              examples:
                '1':
                  value:
                    configurations:
                    - id: '1'
                      name:
                      - locale: en
                        value: friendly name of the conf
                      payload: {}
                    - id: '2'
                      name:
                      - locale: en
                        value: friendly name of the conf2
                      payload: {}
              schema:
                additionalProperties: false
                properties:
                  configurations:
                    items:
                      $ref: ../models/Configuration.v1.yaml
                    type: array
                type: object
          description: OK
      security:
      - Authorization: []
      summary: Get configurations
      tags:
      - Configuration Management
    parameters:
    - in: path
      name: environment_id
      required: true
      schema:
        type: string
    - in: path
      name: view_id
      required: true
      schema:
        type: string
servers:
- description: prod
  url: https://services.utelly.com/configuration_manager/v1
- description: staging
  url: https://staging-services.utelly.com/configuration_manager/v1
- description: dev
  url: https://dev-services.utelly.com/configuration_manager/v1
