openapi: 3.0.0
info:
  title: configuration_manager
  version: v1
  contact:
    name: API Support
    email: developers@utelly.com    
servers:
  - url: 'https://services.utelly.com/configuration_manager/v1'
    description: prod
  - url: 'https://dev-services.utelly.com/configuration_manager/v1'
    description: dev
  - url: 'https://staging-services.utelly.com/configuration_manager/v1'
    description: staging
paths:
  /configurations:
    get:
      summary: Get Configurations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  value:
                    example: example configuration
      operationId: v1.configuration.get
      parameters:
        - schema:
            type: string
          in: query
          name: type
          required: true
        - schema:
            type: string
          in: query
          name: identifier
      description: ''
    post:
      summary: Create Config
      operationId: v1.configuration.post
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  oneOf:
                    - type: string
                      nullable: true
                type:
                  type: string
                config:
                  type: object
            examples:
              '1':
                value:
                  identifier: null
                  type: sherlockConfig
                  config:
                    display_name: LG Demo
                    languages:
                      - en
                    entities:
                      - topic
                      - genre
                      - mood
                      - actor
                      - director
                    enrichments: []
                    options:
                      - phonetic
                      - qualifiers
                      - rest
                    ids_fields:
                      - source_id
                    default_size: 20
                    grouping: entity
                    source: iva_iva
                    SHERLOCK_READ_INDEX: sherlock_iva_iva_read
                    depth: '2'
      description: ''
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
tags:
  - name: utelly_services
