components:
  schemas:
    Consumer:
      description: ''
      type: object
      x-examples:
        example-1:
          _links:
            href: string
          guid: string
          identifiers:
            - id: string
              source: string
          updated_at: string
          created_at: string
          last_interactions:
            - type: string
              entity:
                id: string
                source: string
                type: string
            - kv: {}
      properties:
        _links:
          $ref: ../models/hal_link_field.v1.yaml
        guid:
          type: string
          minLength: 1
          readOnly: true
        identifiers:
          type: array
          items:
            $ref: '#/components/schemas/identifier'
        updated_at:
          type: string
          readOnly: true
        created_at:
          type: string
          readOnly: true
        last_interactions:
          type: array
          items:
            $ref: '#/components/schemas/Interaction'
        kv:
          type: object
    Interaction:
      description: ''
      type: object
      x-examples:
        example-1:
          type: ''
          entity:
            id: ''
            source: ''
            type: ''
      properties:
        type:
          type: string
        entity:
          type: object
          required:
            - id
            - source
          properties:
            id:
              type: string
            source:
              type: string
            type:
              type: string
      required:
        - type
        - entity
    identifier:
      description: ''
      type: object
      properties:
        id:
          type: string
        source:
          type: string
      required:
        - id
        - source
      x-examples:
        example-1:
          id: ''
          source: ''
      title: ''
  securitySchemes:
    Authorization:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: security.check_token
  parameters: {}
  requestBodies:
    consumer:
      content:
        application/json:
          schema:
            type: object
            properties:
              consumer:
                $ref: '#/components/schemas/Consumer'
  responses:
    consumer:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Consumer'
          examples:
            '1':
              value:
                created_at: '2022-03-14T12:42:30Z'
                guid: '123'
                identifiers:
                  - id: '123456'
                    source: test
                kv:
                  city: London
                last_interactions:
                  - entity:
                      guid: '323232'
                      source: utelly
                    type: play
                updated_at: '2022-03-14T12:42:30Z'
info:
  contact:
    email: developers@utelly.com
    name: API Support
  description: ''
  title: consumer_manager
  version: v1
openapi: 3.0.0
paths:
  '/consumers/{consumer_guid}':
    get:
      summary: Get a Consumer
      tags:
        - Consumer Management
      responses:
        '200':
          $ref: '#/components/responses/consumer'
      operationId: v1.consumer.get_one
      description: Retrieve consumer by guid
    parameters:
      - schema:
          type: string
        name: consumer_guid
        in: path
        required: true
    put:
      summary: Update Consumer
      operationId: v1.consumer.put_one
      responses:
        '200':
          $ref: '#/components/responses/consumer'
      requestBody:
        $ref: '#/components/requestBodies/consumer'
      description: Update consumer resource
  /consumers:
    get:
      summary: List Consumers
      tags:
        - Consumer Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _embedded:
                    type: object
                    properties:
                      consumers:
                        type: array
                        items:
                          $ref: '#/components/schemas/Consumer'
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
              examples:
                '1':
                  value:
                    _embedded:
                      consumers:
                        - created_at: '2022-03-14T12:42:30Z'
                          guid: '123'
                          identifiers:
                            - id: '123456'
                              source: test
                          kv:
                            city: London
                          last_interactions:
                            - entity:
                                guid: '323232'
                                source: utelly
                              type: play
                          updated_at: '2022-03-14T12:42:30Z'
                    _links:
                      self:
                        href: string
                      property1:
                        href: string
                      property2:
                        href: string
      operationId: v1.consumer.get_list
      parameters:
        - schema:
            type: string
          in: query
          name: filters
          description: json value of the Filters object
        - schema:
            type: string
          in: query
          name: after_guid
        - schema:
            type: string
          in: query
          name: before_guid
        - schema:
            type: string
          in: query
          name: before_or_eq_guid
        - schema:
            type: array
            items:
              type: string
          in: query
          name: fields
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: skip
        - schema:
            type: array
            items:
              type: string
          in: query
          name: sort
      description: Retrieve consumers
    post:
      summary: Create Consumer
      operationId: v1.consumer.post_one
      responses:
        '200':
          $ref: '#/components/responses/consumer'
      description: ''
      requestBody:
        $ref: '#/components/requestBodies/consumer'
      tags:
        - Consumer Management
servers:
  - description: prod
    url: 'https://services.utelly.com/consumer_manager/v1'
  - description: staging
    url: 'https://staging-services.utelly.com/consumer_manager/v1'
  - description: dev
    url: 'https://dev-services.utelly.com/consumer_manager/v1'
tags:
  - name: utelly_services
security:
  - Authorization: []
