openapi: 3.0.0
info:
  title: discover_manager
  version: v1
  description: ''
servers:
  - url: 'https://services.utelly.com/discover_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/discover_manager/v1'
    description: staging
  - url: 'https://services-dev.utelly.com/discover_manager/v1'
    description: dev
paths:
  /creative_works/discover:
    get:
      summary: Discover Creative Works
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                additionalProperties: false
                type: object
                properties:
                  _embedded:
                    additionalProperties: false
                    type: object
                    properties:
                      creative_works:
                        type: array
                        items:
                          $ref: ./browse_manager.v1.yaml#/components/schemas/CreativeWork
                  _links:
                    $ref: ../models/HalLinks.v1.yaml
                required:
                  - _embedded
                  - _links
              examples:
                '1':
                  value:
                    _embedded:
                      creative_works:
                        - _links:
                            availabilities:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/availabilities
                            content_ratings:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/content_ratings
                            contributors:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/contributors
                            episodes:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/episodes
                            seasons:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/seasons
                            self:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46
                            tags:
                              href: /content/creative_works/27c13eec19014084a0a3173061702b46/tags
                          artworks:
                            - height: 100
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: poster
                              url: 'https://mydomain.com/poster.jpg'
                              width: 100
                          created_at: '2020-01-01T00:00:10Z'
                          deleted: false
                          descriptions:
                            - description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.'
                              metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: full
                          guid: 27c13eec19014084a0a3173061702b46
                          identifiers:
                            - id: '1'
                              source: mysource
                          relationships:
                            - href: /content/creative_works/eac7cb1192264b088ccbad0874395ce5
                              rel: parent
                          titles:
                            - metadata:
                                country: GB
                                language: en
                                source: mysource
                                type: official
                              title: The Usual Suspects
                          type: movie
                          updated_at: '2020-01-01T00:00:10Z'
                    _links:
                      first:
                        href: /content/creative_works
                      last:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      next:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
                      prev:
                        href: /content/creative_works
                      self:
                        href: /content/creative_works?after_guid=8703dd1ced974ecea01116f2c0a5a282&limit=50
      operationId: v1.discover.creative_work.get
      parameters:
        - schema:
            type: array
            items:
              type: string
          in: query
          name: channels
          style: form
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: release_years
          style: form
        - schema:
            type: array
            items:
              type: string
          in: query
          name: content_ratings
          style: form
        - schema:
            type: array
            items:
              type: string
          in: query
          name: genres
          style: form
        - schema:
            type: array
            items:
              type: string
          in: query
          name: types
          style: form
        - schema:
            type: array
            items:
              type: string
          in: query
          name: guids
          style: form
        - schema:
            type: array
            items:
              type: string
          in: query
          name: titles
          style: form
        - schema:
            type: string
            enum:
              - popularity
              - relevancy
              - release_year
              - recommendation
              - rating
          in: query
          name: order_by
        - schema:
            type: integer
          in: query
          name: refresh_rate
        - schema:
            type: array
            items:
              type: integer
          in: query
          name: title_shuffle_set
          style: form
        - schema:
            type: integer
          in: query
          name: shuffle_rate
        - schema:
            type: integer
            minimum: 0
            maximum: 50
          in: query
          name: limit
        - schema:
            type: array
            items:
              $ref: ../models/integer_range_field.v1.yaml
          in: query
          name: durations
          style: form
      description: ''
