openapi: 3.0.0
info:
  title: interaction_manager
  version: '1.0'
  description: Interactions base API
servers:
  - url: 'http://localhost:3000'
paths:
  /interactions:
    parameters: []
    get:
      summary: List all Interactions
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interaction'
              examples:
                example-1:
                  value:
                    - type: watch
                      cascade_create: false
                      created_at: '2019-08-24T14:15:22Z'
                      target_guid: string
                      context:
                        platform: ios
                        duration: 0
                        price: 0
                        rating: -1
                        session_guid: string
                        portion: 0
        '201':
          description: Created
        '400':
          description: Bad Request
      operationId: get-users-user_id-interactions
    post:
      summary: ''
      operationId: post-users-user_id-interactions
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interaction'
            examples:
              example-1:
                value:
                  type: watch
                  cascade_create: false
                  created_at: '2019-08-24T14:15:22Z'
                  target_guid: string
                  context:
                    platform: ios
                    duration: 0
                    price: 0
                    rating: -1
                    session_guid: string
                    portion: 0
components:
  schemas:
    Interaction:
      title: Interaction
      type: object
      x-examples:
        example-1:
          created_at: '2019-08-24T14:15:22Z'
          context:
            platform: web
            duration_secs: 0
            value: 0
            rating: 0
            discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
            portion: 0
            quantity: 0
          user:
            id: f6a546e0eccd3fbfbdb7d6d9378f8318f79311b6bd9885582021192226219a32
            source: stv
          entity:
            id: '@E#R%#@$%@$%$23325234'
            source: utelly
            type: movie
          type:
            type: watch
        example-2:
          created_at: '2019-08-24T14:15:22Z'
          context:
            platform: web
            duration_secs: 0
            value: 0
            rating: 0
            discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
            portion: 0
            quantity: 0
          user:
            id: f6a546e0eccd3fbfbdb7d6d9378f8318f79311b6bd9885582021192226219a32
            source: stv
          entity:
            id: '@E#R%#@$%@$%$23325234'
            source: utelly
            type: movie
          type: bookmark
        example-3:
          created_at: '2019-08-24T14:15:22Z'
          context:
            platform: web
            duration_secs: 0
            value: 0
            rating: 0
            discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
            portion: 0
            quantity: 0
          user:
            id: f6a546e0eccd3fbfbdb7d6d9378f8318f79311b6bd9885582021192226219a32
            source: stv
          entity:
            id: '@E#R%#@$%@$%$23325234'
            source: utelly
            type: movie
          type: bookmark
        example-4:
          created_at: '2019-08-24T14:15:22Z'
          context:
            platform: web
            duration_secs: 0
            value: 0
            rating: 0
            discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
            portion: 0
            quantity: 0
          user:
            id: f6a546e0eccd3fbfbdb7d6d9378f8318f79311b6bd9885582021192226219a32
            source: stv
          entity:
            id: af1234de276458
            source: utelly
            type: movie
          type: bookmark
          nested_type:
            platform: web
            duration_secs: 0
            value: 0
            rating: 0
            discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
            portion: 0
            quantity: 0
      description: 'This model represents the interaction between a user and an object (creative works, people, tags, etc...).'
      properties:
        created_at:
          format: date-time
          type: string
          description: UTC timestamp of the view as ISO8601-1 pattern or UTC epoch time. The default value is the current time.
          readOnly: true
        context:
          type: object
          description: 'Generalpurpose object to collect info that is very context dependant, esp of the type of interaction we record'
          properties:
            platform:
              type: string
              enum:
                - ios
                - android
                - web
                - chromecast
                - firetv
                - roku
                - ctv_samsung
                - ctv_lg
                - ctv_sony
                - ctv_philips
                - ctv_panasonic
                - ctv_hisense
                - ctv_xiaomi
                - ctv_other
                - stb_other
                - stb_youview
                - stb_virginmedia
                - stv_sky
                - stb_freeview
                - stb_freesat
              description: Which platform did the interaction take place on?
              default: web
            duration_secs:
              type: integer
              minimum: 0
              format: int64
              description: 'How long did the interaction last, in seconds?'
            value:
              type: number
              format: float
              minimum: 0
              description: A value associated with the interaction.
            rating:
              type: number
              multipleOf: 0
              minimum: -1
              maximum: 1
              format: float
              description: A rating associated with the interaction
              example: 0
            discover_guid:
              type: string
              description: A guid to tie back the interaction to recommended content
              example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
            portion:
              type: number
              format: float
              minimum: 0
              maximum: 1
              default: 0
              description: '% of the target object interacted with. Can be the length of the content watched'
            quantity:
              type: number
              format: float
              description: 'quantity of object(s) interacted with. For instance, user bought 2 tickets for a movie.'
        user:
          type: object
          properties:
            id:
              type: string
              example: f6a546e0eccd3fbfbdb7d6d9378f8318f79311b6bd9885582021192226219a32
            source:
              type: string
              example: stv
        entity:
          type: object
          properties:
            id:
              type: string
              example: af1234de276458
            source:
              type: string
              example: utelly
            type:
              $ref: '#/components/schemas/entity_type_field'
        type:
          $ref: '#/components/schemas/interaction_type_field'
        nested_type:
          $ref: '#/components/schemas/interaction_bookmark'
      required:
        - created_at
    entity_type_field:
      type: string
      enum:
        - movie
        - series
        - tv program
        - podcast
        - website
        - article
    interaction_type_field:
      type: string
      title: interaction_type_field
      enum:
        - bookmark
        - rate
        - view
        - buy
        - rent
        - play
      x-examples:
        example-1: bookmark
    interaction_bookmark:
      title: interaction_bookmark
      type: object
      description: 'Generalpurpose object to collect info that is very context dependant, esp of the type of interaction we record'
      properties:
        platform:
          type: string
          enum:
            - ios
            - android
            - web
            - chromecast
            - firetv
            - roku
            - ctv_samsung
            - ctv_lg
            - ctv_sony
            - ctv_philips
            - ctv_panasonic
            - ctv_hisense
            - ctv_xiaomi
            - ctv_other
            - stb_other
            - stb_youview
            - stb_virginmedia
            - stv_sky
            - stb_freeview
            - stb_freesat
          description: Which platform did the interaction take place on?
          default: web
        duration_secs:
          type: integer
          minimum: 0
          format: int64
          description: 'How long did the interaction last, in seconds?'
        value:
          type: number
          format: float
          minimum: 0
          description: A value associated with the interaction.
        rating:
          type: number
          multipleOf: 0
          minimum: -1
          maximum: 1
          format: float
          description: A rating associated with the interaction
          example: 0
        discover_guid:
          type: string
          description: A guid to tie back the interaction to recommended content
          example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
        portion:
          type: number
          format: float
          minimum: 0
          maximum: 1
          default: 0
          description: '% of the target object interacted with. Can be the length of the content watched'
        quantity:
          type: number
          format: float
          description: 'quantity of object(s) interacted with. For instance, user bought 2 tickets for a movie.'
      x-examples:
        example-1: {}
        example-2:
          platform: web
          duration_secs: 0
          value: 0
          rating: 0
          discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
          portion: 0
          quantity: 0
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
security:
  - Authorization: []
