openapi: 3.0.0
info:
  title: interaction_manager
  version: '1.0'
  description: Interactions base API
servers:
  - url: 'http://localhost:3000'
paths:
  /interactions:
    parameters: []
    get:
      summary: List all Interactions
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interaction'
              examples:
                example-1:
                  value:
                    - type: watch
                      cascade_create: false
                      created_at: '2019-08-24T14:15:22Z'
                      target_guid: string
                      context:
                        platform: ios
                        duration: 0
                        price: 0
                        rating: -1
                        session_guid: string
                        portion: 0
        '201':
          description: Created
        '400':
          description: Bad Request
      operationId: get-users-user_id-interactions
    post:
      summary: ''
      operationId: post-users-user_id-interactions
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interaction'
            examples:
              example-1:
                value:
                  type: watch
                  cascade_create: false
                  created_at: '2019-08-24T14:15:22Z'
                  target_guid: string
                  context:
                    platform: ios
                    duration: 0
                    price: 0
                    rating: -1
                    session_guid: string
                    portion: 0
components:
  schemas:
    Interaction:
      title: Interaction
      x-examples:
        example-1:
          platform: ios
          discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
          type: bookmark
          created_at: '2019-08-24T14:15:22Z'
          id: string
          source: string
        example-2:
          platform: ios
          discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
          type: bookmark
          created_at: '2019-08-24T14:15:22Z'
          id: string
          source: string
        example-3:
          platform: ios
          discover_guid: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
          type: bookmark
          created_at: '2019-08-24T14:15:22Z'
          user:
            id: string
            source: string
          entity:
            id: string
            source: string
            type: movie
      description: 'This model represents the interaction between a user and an object (creative works, people, tags, etc...).'
      allOf:
        - anyOf:
            - $ref: '#/components/schemas/interaction_bookmark'
            - $ref: '#/components/schemas/interaction_play'
            - $ref: '#/components/schemas/interaction_view'
            - $ref: '#/components/schemas/interaction_buy_rent'
            - $ref: '#/components/schemas/interaction_rate'
        - type: object
          properties:
            created_at:
              type: string
              format: date-time
            user:
              $ref: '#/components/schemas/user'
            entity:
              $ref: '#/components/schemas/entity'
    entity_type:
      type: string
      enum:
        - movie
        - series
        - tv program
        - podcast
        - website
        - article
        - person
        - location
        - tag
      title: entity type
    interaction_type:
      type: string
      title: interaction_type
      enum:
        - bookmark
        - rate
        - view
        - buy
        - rent
        - play
      x-examples:
        example-1: bookmark
    interaction_bookmark:
      title: interaction_bookmark
      type: object
      description: 'General purpose object to collect info that is very context dependant, esp of the type of interaction we record'
      x-examples: {}
      properties:
        platform:
          $ref: '#/components/schemas/platform_type'
        discover_guid:
          type: string
          description: A guid to tie back the interaction to recommended content
          example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
        type:
          type: string
          enum:
            - bookmark
    interaction_rate:
      title: interaction_rate
      type: object
      description: 'Generalpurpose object to collect info that is very context dependant, esp of the type of interaction we record'
      x-examples: {}
      properties:
        platform:
          $ref: '#/components/schemas/platform_type'
        rating:
          type: number
          multipleOf: 0
          minimum: -1
          maximum: 1
          format: float
          description: A rating associated with the interaction
          example: 0
        discover_guid:
          type: string
          description: A guid to tie back the interaction to recommended content
          example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
        type:
          type: string
          enum:
            - rate
    interaction_view:
      title: interaction_view
      type: object
      description: 'Generalpurpose object to collect info that is very context dependant, esp of the type of interaction we record'
      x-examples: {}
      properties:
        platform:
          $ref: '#/components/schemas/platform_type'
        discover_guid:
          type: string
          description: A guid to tie back the interaction to recommended content
          example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
        type:
          type: string
          enum:
            - view
    interaction_play:
      title: interaction_play
      type: object
      description: 'Generalpurpose object to collect info that is very context dependant, esp of the type of interaction we record'
      x-examples: {}
      properties:
        platform:
          $ref: '#/components/schemas/platform_type'
        duration_secs:
          type: integer
          minimum: 0
          format: int64
          description: 'How long did the interaction last, in seconds?'
        discover_guid:
          type: string
          description: A guid to tie back the interaction to recommended content
          example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
        portion:
          type: number
          format: float
          minimum: 0
          maximum: 1
          default: 0
          description: '% of the target object interacted with. Can be the length of the content watched'
        type:
          type: string
          enum:
            - play
    interaction_buy_rent:
      title: interaction_buy_rent
      type: object
      description: 'Generalpurpose object to collect info that is very context dependant, esp of the type of interaction we record'
      x-examples: {}
      properties:
        platform:
          $ref: '#/components/schemas/platform_type'
        value:
          type: number
          format: float
          minimum: 0
          description: A value associated with the interaction.
        discover_guid:
          type: string
          description: A guid to tie back the interaction to recommended content
          example: 5e987e47-7ed0-4442-a3bb-e3aeacd4840c
        quantity:
          type: number
          format: float
          description: 'quantity of object(s) interacted with. For instance, user bought 2 tickets for a movie.'
        type:
          type: string
          enum:
            - buy
            - rent
    platform_type:
      type: string
      title: platform_type
      enum:
        - ios
        - android
        - web
        - chromecast
        - firetv
        - roku
        - ctv_samsung
        - ctv_lg
        - ctv_sony
        - ctv_philips
        - ctv_panasonic
        - ctv_hisense
        - ctv_xiaomi
        - ctv_other
        - stb_other
        - stb_youview
        - stb_virginmedia
        - stv_sky
        - stb_freeview
        - stb_freesat
    user:
      title: user
      type: object
      properties:
        id:
          type: string
        source:
          type: string
    entity:
      title: entity
      type: object
      properties:
        id:
          type: string
        source:
          type: string
        type:
          $ref: '#/components/schemas/entity_type'
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
security:
  - Authorization: []
