openapi: 3.0.0
info:
  title: log_manager
  version: '1.0'
  description: Log manager for the Utelly API platform
servers:
  - url: 'https://utellapis.com/log_manager/v1'
    description: prod
  - url: 'https://dev-utellapis.com/log_manager/v1'
    description: dev
  - url: 'https://staging-utellapis.com/log_manager/v1'
    description: staging
paths: {}
components:
  schemas: {}
