openapi: 3.0.0
info:
  title: log_manager
  version: '1.0'
  description: Log manager for the Utelly API platform
servers:
  - url: 'https://utellapis.com/log_manager/v1'
    description: prod
  - url: 'https://dev-utellapis.com/log_manager/v1'
    description: dev
  - url: 'https://staging-utellapis.com/log_manager/v1'
    description: staging
paths:
  /log:
    post:
      summary: ''
      operationId: app.post_log
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Log'
      security:
        - Authorization: []
  /logs:
    post:
      summary: ''
      operationId: app.post_logs
      responses:
        '200':
          description: OK
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Log'
    parameters: []
components:
  schemas:
    Log:
      title: Log
      type: object
      x-examples:
        '1':
          timestamp: 1583934547
          variant: utellygn
          app_key: 36a637a56e184748b0470e50e6242901
          system_name: user_manager
          version: 2
          payload:
            message: pipeline successfully created
      properties:
        timestamp:
          type: integer
        variant:
          type: string
        app_key:
          type: string
        payload:
          type: object
        system_name:
          type: string
        version:
          type: number
      required:
        - timestamp
        - variant
        - app_key
        - payload
        - system_name
        - version
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      description: ''
      x-apikeyInfoFunc: app.check_token