openapi: 3.0.0
info:
  title: security_manager
  version: v1
servers:
  - url: 'https://services.utelly.com/security_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/security_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/security_manager/v1'
    description: dev
paths:
  /authenticate:
    post:
      summary: Authenticate
      operationId: v1.user.authenticate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  refresh_token:
                    type: string
                required:
                  - id
                  - access_token
                  - refresh_token
              examples:
                '1':
                  value:
                    id: 9b38b54dd74644db96e772d6076615da
                    access_token: 9b38b54dd74644db96e772d6076615da
                    refresh_token: f9a664c1ba3f4665aa902ded47edaca9
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            examples:
              '1':
                value:
                  email: hello@utelly.com
                  password: 3@Ubc1iCYZUKGtAi
        description: ''
      description: Authenticates a user
      tags:
        - Authentication Management
  /refresh_jwt_token:
    post:
      summary: ''
      operationId: v1.user.refresh_jwt_token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                required:
                  - access_token
              examples:
                '1':
                  value:
                    access_token: f9a664c1ba3f4665aa902ded47edaca9
            application/xml:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
                - refresh_token
            examples:
              '1':
                value:
                  refresh_token: cc53ca4aaf294c489a29c1515cb1f1b3
      tags:
        - Authentication Management
components:
  schemas: {}
  securitySchemes: {}
