openapi: 3.0.0
info:
  title: user_manager
  version: v1
servers:
  - url: 'https://services.utelly.com/user_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/user_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/user_manager/v1'
    description: dev
paths:
  /user/roles:
    parameters: []
    get:
      summary: Get user roles
      tags:
        - User Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      $ref: ../models/Role.v1.yaml
                required:
                  - roles
              examples:
                '1':
                  value:
                    roles:
                      - perspective_id: '1'
                        module_id: '1'
                        environment_id: '1'
                        permission: read
      operationId: v1.user.get_roles
      security:
        - Authorization: []
      description: Get user roles
  /user/preferences:
    parameters: []
    get:
      summary: Get user preferences
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  values:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: ../models/kv_field.v1.yaml
                required:
                  - values
              examples:
                '1':
                  value:
                    values:
                      - key: default_env
                        value: '1'
                      - key: default_perspective
                        value: '1'
                      - key: default_module
                        value: '1'
      operationId: v1.user.get_preferences
      security:
        - Authorization: []
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      x-apikeyInfoFunc: security.check_token
