openapi: 3.0.0
info:
  title: user_manager
  version: v1
servers:
  - url: 'https://services.utelly.com/user_manager/v1'
    description: prod
  - url: 'https://staging-services.utelly.com/user_manager/v1'
    description: staging
  - url: 'https://dev-services.utelly.com/user_manager/v1'
    description: dev
paths:
  '/user/{user_id}/roles':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: Get user roles
      tags:
        - User Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      $ref: './broker_app.v1.yaml#/components/schemas/Role'
                required:
                  - roles
              examples:
                '1':
                  value:
                    roles:
                      - perspective_id: 1
                        module_id: 1
                        environment_id: 1
                        permission: login_to_portal
      operationId: v1.user.get_roles
      security:
        - Authorization: []
      description: Get user roles
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
      x-apikeyInfoFunc: security.check_token
