openapi: 3.0.0
info:
  title: user_manager
  version: v1
servers:
  - url: 'https://utellapis.com/user_manager/v1'
    description: prod
  - url: 'https://staging.utellapis.com/user_manager/v1'
    description: staging
  - url: 'https://dev.utellapis.com/user_manager/v1'
    description: dev
paths:
  '/user/{user_id}/roles':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    get:
      summary: Get user roles
      tags:
        - User Management
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roles:
                    type: array
                    items:
                      type: string
                required:
                  - roles
              examples:
                '1':
                  value:
                    roles: []
      operationId: v1.user.get_roles
      security:
        - Authorization: []
      description: Get user roles
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: Authorization
      type: apiKey
      in: header
