additionalProperties: false
properties:
  id:
    type: string
  name:
    items:
      $ref: ./i18n_field.v1.yaml
    type: array
  payload:
    additionalProperties: false
    type: object
required:
- id
- name
- payload
title: Configuration
type: object
x-examples:
  '1':
    id: '1'
    name: friendly name of the conf
    payload: {}
x-tags:
- Models
